hugover = "0.69.0"

[[serve]]
key = "default"
config = "config.toml"

[[build]]
key = "default"
config = "config.toml"

[[collections]]
key = "posts"
title = "Posts"
folder = "content/posts/"
extension = "md"
dataformat = "toml"
itemtitle = "Post"

  [[collections.fields]]
  key = "info"
  type = "info"
  content = "# Info\nYou can write custom instructions here."
  size = "default"
  lineHeight = 1.2
  theme = "default"

  
[[collections]]
key = "oilseeds"
title = "oil-seeds"
itemtitle = "Oil-seeds"
folder = "content/english/oil-seeds/"
extension = "md"
dataformat = "yaml"

  [[collections.fields]]
  key = "title"
  type = "string"
  title = "Title"
  required = false
  pattern = ""
  multiLine = false
  default = ""
  tip = ""

  [[collections.fields]]
  key = "slug"
  type = "string"
  title = "Slug"
  required = false
  pattern = ""
  multiLine = false
  default = ""
  tip = ""

  [[collections.fields]]
  key = "date"
  type = "date"
  title = "Date"
  required = false
  tip = ""

  [[collections.fields]]
  key = "draft"
  type = "boolean"
  title = "Draft"
  default = false
  tip = ""

  [[collections.fields]]
  key = "productimage"
  type = "string"
  title = "Productimage"
  required = false
  pattern = ""
  multiLine = false
  default = ""
  tip = ""

  [[collections.fields]]
  key = "producttitle"
  type = "string"
  title = "Product title"
  required = false
  pattern = ""
  multiLine = false
  default = ""
  tip = ""

  [[collections.fields]]
  key = "productdescription"
  type = "string"
  title = "Product description"
  required = false
  pattern = ""
  multiLine = true
  default = ""
  tip = ""

  [[collections.fields]]
  key = "page_header_bg"
  type = "string"
  title = "page header bg"
  required = false
  pattern = ""
  multiLine = false
  default = ""
  tip = ""

  [[collections.fields]]
  key = "leftbgimg"
  type = "string"
  title = "left bg img"
  required = false
  pattern = ""
  multiLine = false
  default = ""
  tip = ""

  [[collections.fields]]
  key = "rightbgimg"
  type = "string"
  title = "right bg img"
  required = false
  pattern = ""
  multiLine = false
  default = ""
  tip = ""

  [[collections.fields]]
  key = "bundle-manager-images"
  type = "bundle-manager"
  title = "Bundle Manager: Images"
  path = "images"
  extensions = [
    "png",
    "jpg",
    "svg",
    "gif"
  ]

    [[collections.fields.fields]]
    key = "title"
    type = "string"
    title = "Title"
    required = false
    pattern = ""
    multiLine = false
    default = ""
    tip = ""

    [[collections.fields.fields]]
    key = "featured"
    type = "boolean"
    title = "Featured"
    default = false
    tip = ""

    [[collections.fields.fields]]
    key = "thumb"
    type = "bundle-image-thumbnail"
    src = "Thubmanil"

  [[collections.fields]]
  key = "mainContent"
  type = "markdown"
  title = "Content"
  multiLine = true
  default = ""
  tip = ""

  [[collections.fields]]
  key = "productimagebanner"
  type = "string"
  title = "product image banner"
  required = false
  pattern = ""
  multiLine = false
  default = ""
  tip = ""

[[singles]]
key = "mainConfig"
title = "Main Config"
file = "config.toml"
dataformat = "toml"

  [[singles.fields]]
  key = "title"
  title = "Site Title"
  type = "string"
  tip = "Your page title."
  required = false
  pattern = ""
  multiLine = false
  default = ""

  [[singles.fields]]
  key = "baseURL"
  title = "Base URL"
  type = "string"
  tip = "Your site URL."
  required = false
  pattern = ""
  multiLine = false
  default = ""

  [[singles.fields]]
  key = "theme"
  title = "Theme"
  type = "readonly"
  tip = "The current theme."
  required = false
  value = ""
  default = ""
  multiLine = false

  [[singles.fields]]
  key = "languageCode"
  title = "Language Code"
  type = "readonly"
  required = false
  value = ""
  default = ""
  multiLine = false
  tip = ""

  [[singles.fields]]
  key = "googleAnalytics"
  title = "Google Analytics"
  type = "string"
  tip = "Provide a Google Analitics Tracking Code to enable analytics."
  required = false
  pattern = ""
  multiLine = false
  default = ""

  [[singles.fields]]
  key = "enableRobotsTXT"
  title = "Enable Robots"
  type = "boolean"
  default = true
  tip = "If you want your page to be indexed, keep this enabled."