backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
collections:
  - name: "aboutus" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "about us" # Used in the UI, ie.: "New Post"
    folder: "content/english/aboutus" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page header image", name: "page_header_bg", widget: "image" }
      - { label: "Meta description", name: "metadescription", widget: "text" }
      - { label: "About title", name: "abouttitle", widget: "string" }
      - { label: "Main content", name: "content", widget: "text" }
      - { label: "Services header", name: "boxtitle1", widget: "string" }
      - { label: "Services content", name: "boxcontent1", widget: "text" }
      - { label: "Vision header", name: "boxtitle2", widget: "string" }
      - { label: "Vision content", name: "boxcontent2", widget: "text" }
